import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const aeonik = localFont({
  src: [
    {
      path: "../../public/fonts/aeonik-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap", // troca rápido, otimiza CLS
});

export const metadata: Metadata = {
  title: "Newarch - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="light" suppressHydrationWarning>
      <body className={`${aeonik.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
